Updating...

diff --git a/Auto/Exp/Csh/Account b/Auto/Exp/Csh/Account
--- a/Auto/Exp/Csh/Account
+++ b/Auto/Exp/Csh/Account
@@ -14,35 +14,64 @@ set Types = ('Pay_IN' 'Pay_OUT' 'Transfers(Self)' 'Transfers(3rd-Party)');
 #------------------------------------------------1st Arg...
 if ( $#argv ) then
         set ARGV1 = $argv[1]
+        shift
         goto HasARGV1
 else
 	goto GetARGV1
 endif
 GetARGV1:
-set ARGV1 = '-'`zenity --list --title "Mode" --text "What do you wish to do..." --column '' "Setup" "Add" "Delete" "Record"`
+set ARGV1 = '--'`zenity --list --title "Mode" --text "What do you wish to do..." --column '' "Setup" "Add-Account" "Add-Person" "Delete-Account" "Record"`
 #------------------------------------------------1st Arg Process...
 HasARGV1:
 set ARGV1 = `echo $ARGV1 | tr 'A-Z' 'a-z'`
 switch ( $ARGV1 )
-case "-setup":
-	if ( ! -e $MyDir ) then
-		mkdir -p $MyDir/Books $MyDir/Sources $MyDir/Accounts
-		echo '"Title","Balance"'                                 | tee $MyDir/accounts.csv | tee $MyDir/sources.csv > $MyDir/3rd-party.csv
-		echo '"Date","Trsc Type","Comment","From","To","Amount"' | tee $MyDir/Books/`date +%Y`_Book.csv > $MyDir/Books/`date +%Y%m`_Book.csv
-		find $MyDir -type f -name '*.csv' -exec md5sum '{}' \;  >! $MyDir/.checksum.log
-	else
-		echo "WARNING : Directory already exists"
-	endif
-	exit 0
+case "--setup":
+        goto Setup
 	breaksw
+case "--add-account":
+        goto AddAccount
+        breaksw
+case "--add-person":
+        goto AddPerson
+        breaksw
+case "--delete-account":
+        goto DeleteAccount
+        breaksw
+case "--record":
+        goto Record
+        breaksw
+default:
+        echo "# Invalid First option"
+        goto GetARGV1
+        breaksw
 endsw
-#------------------------------------------------checksum...
-md5sum -c $MyDir/.checksum.log | sed '/OK/d'
-if ( $? ) then
-	echo "CheckSUM failed due to modification in above files"
-	exit 9
+#------------------------------------------------Setup...
+Setup:
+if ( ! -e $MyDir ) then
+        mkdir -p $MyDir/Books $MyDir/SrcBooks $MyDir/AccBooks
+        echo '"Title","Balance"'                                        | tee $MyDir/accounts.csv | tee $MyDir/sources.csv > $MyDir/3rd-party.csv
+        echo '"Date","Transaction Type","Comment","From","To","Amount"' | tee $MyDir/Books/`date +%Y`_Book.csv > $MyDir/Books/`date +%Y%m`_Book.csv
+        find $MyDir -type f -name '*.csv' -exec sha512sum '{}' \;       >! $MyDir/.checksum.log
+else
+        echo "# ERROR : Directory already exists"
+        exit 1
 endif
-#------------------------------------------------Reading Args...
+#------------------------------------------------checksum...
+sha512sum -c $MyDir/.checksum.log | sed -n '/OK/!p'
+if ( $? ) then
+        echo "CheckSUM failed due to modification in above files"
+        exit 9
+endif
+#------------------------------------------------(AddAccount) Reading ARGS - CMD line...
+AddAccount:
+if ( $#argv ) then
+        set Account = $argv[1]
+else
+        set Account = `zenity --entry --title "Add-Account" --text "Please enter Title of Account..."`
+endif
+
+AddPerson:
+#------------------------------------------------(Record) Reading ARGS - CMD line...
 Record:
 while ( $#argv > 0 )
         set Option = `echo $1 | tr 'A-Z' 'a-z'`
@@ -82,7 +111,7 @@ while ( $#argv > 0 )
                 breaksw
         endsw
 end
-#------------------------------------------------Validating data...
+#------------------------------------------------(Record) Reading - ARGS GUI...
 if ( ! $?Amount  ) @   Amount  = `zenity --entry --title "Amount"  --text "Please enter an AMOUNT..."`
 if ( ! $?Comment ) set Comment = `zenity --entry --title "Comment" --text "Please COMMENT on transaction..."`
 if ( ! $?Type    ) set Type    = `zenity --list  --title "Types"   --text "Please select one of the TYPES" --column "Types" $Types`
@@ -91,7 +120,6 @@ if ( ! $?Type    ) set Type    = `zenity --list  --title "Types"   --text "Pleas
 set From = From
 set To = To
 #------------------------------------------------Pre Process...
-#if (-e -f ~/)
 #------------------------------------------------Confirm what is being recorded...
 zenity --question --title "Confirm" --text "Date\t\t$Date\nAmount\t$Amount\nType\t\t$Type\nComment\t$Comment\nFrom\t\t$From\nTo\t\t$To" >&! /dev/null
 if ( $? ) then
